service: vus-backend-lambda
frameworkVersion: '2'
disabledDeprecations:
    - CLI_OPTIONS_SCHEMA
useDotenv: true
plugins:
    - serverless-offline
    - serverless-dotenv-plugin

provider:
    name: aws
    runtime: nodejs12.x
    region: ap-northeast-2
    lambdaHashingVersion: 20201221
    apiGateway: { shouldStartNameWithService: true }

functions:
    graphql:
        handler: src/handler.graphqlHandler
        events:
            - http:
                  path: graphql
                  method: any
                  cors: true
